package dev.vrm.runtime.core.motion

import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * MotionSpec — a keyframe-animation description generated by an LLM from a
 * natural-language motion request (port of text-to-vrma's motion spec JSON).
 *
 * It is the ENGINE-AGNOSTIC middle format between "LLM says what to do" and
 * "engine makes the skeleton move". [MotionSpecClipBuilder] turns it into a
 * [dev.vrm.runtime.core.vrma.VRMAnimationClip] that the existing
 * [dev.vrm.runtime.adapter.VrmAnimationPlayer] can play, so no new player is
 * needed.
 *
 * Coordinate conventions (VRM 1.0 / T-pose rest, matching three-vrm):
 *  - model faces +Z, +X is the model's left hand side, +Y up
 *  - rotations are Euler angles [X, Y, Z] in DEGREES, XYZ order, from the
 *    T-pose rest
 *  - bone names are the VRM human-bone names (leftUpperArm, spine, head, ...)
 *  - hips `p` is a local translation OFFSET in metres from rest
 *  - expression weights are 0..1
 *
 * Example:
 * ```json
 * {
 *   "name": "bow", "duration": 2.4, "loop": false,
 *   "tracks": { "spine": [ { "t": 0, "r": [0,0,0] }, { "t": 0.7, "r": [22,0,0] } ] },
 *   "hips": [ { "t": 0, "p": [0,0,0] } ],
 *   "expressions": { "happy": [ { "t": 0, "w": 0 }, { "t": 1, "w": 0.7 } ] }
 * }
 * ```
 */
@Serializable
data class MotionSpec(
    val name: String = "motion",
    /** Duration in seconds. */
    val duration: Float = 1f,
    val loop: Boolean = false,
    /** bone name -> rotation keyframes (Euler degrees, XYZ order). */
    val tracks: Map<String, List<RotKey>> = emptyMap(),
    /** hips translation-offset keyframes (metres, from rest). */
    val hips: List<PosKey> = emptyList(),
    /** expression preset name -> weight keyframes 0..1. */
    val expressions: Map<String, List<WeightKey>> = emptyMap(),
) {
    companion object {
        private val JSON = Json { ignoreUnknownKeys = true }

        /** Parse a MotionSpec from LLM JSON text. Throws on invalid JSON. */
        fun fromJson(text: String): MotionSpec = JSON.decodeFromString<MotionSpec>(text)
    }
}

/** A rotation keyframe: [t] time in seconds, [r] Euler [X,Y,Z] degrees. */
@Serializable
data class RotKey(
    val t: Float = 0f,
    val r: List<Float> = emptyList(),
)

/** A position keyframe: [t] time in seconds, [p] offset [x,y,z] metres. */
@Serializable
data class PosKey(
    val t: Float = 0f,
    val p: List<Float> = emptyList(),
)

/** An expression-weight keyframe: [t] time in seconds, [w] weight 0..1. */
@Serializable
data class WeightKey(
    val t: Float = 0f,
    val w: Float = 0f,
)
